#!/usr/bin/env ruby

require 'fileutils'
require 'pry-byebug'
require_relative 'models/base.rb'
require_relative 'models/issue.rb'
require_relative 'models/post.rb'
require_relative 'models/static.rb'

Base.set_source_dir(File.join(Dir.pwd, 'src'))

if ARGV[0] == "local"
  Base.set_host(File.join(Dir.pwd, 'dev_docs'))
  Base.set_dest_dir(File.join(Dir.pwd, 'dev_docs'))
else
  Base.set_host("https://delayfiction.org")
  Base.set_dest_dir(File.join(Dir.pwd, 'docs'))
end

# copy assets to the right places
assets_dir = File.join Base.dest_dir, 'assets'
FileUtils.mkdir(Base.dest_dir) unless Dir.exist?(Base.dest_dir)
FileUtils.mkdir(assets_dir) unless Dir.exist?(assets_dir)

`cp -r #{File.join Base.source_dir, 'assets', '.'} #{File.join Base.dest_dir, 'assets'}`
`cp -r #{File.join Base.source_dir, 'auto_assets', '.'} #{File.join Base.dest_dir}`

Issue.all(File.join(Base.source_dir, 'data', 'issues')).each do |issue|
  #make dir for issue
  directory = File.join Base.dest_dir, issue.id
  FileUtils.mkdir(directory) unless Dir.exist?(directory)

  #write issue
  File.write(
    File.join(directory, (issue.id + '.html')),
    issue.render('show-issue')
  )

  #write stories
  issue.stories.each do |story|
    File.write(
      File.join(directory, (story.id + '.html')),
      story.render('show-post')
    )
  end
end

Static.all(File.join(Base.source_dir, 'data', 'static')).each do |static|
  File.write(
    File.join(Base.dest_dir, (static.id + '.html')),
    static.render('show-static')
  )
end
